In [1]:
import numpy as np
import pandas as pd
import requests

In [4]:
url = 'https://api.worldbank.org/v2/country/all/indicator/FP.CPI.TOTL.ZG?format=json&per_page=20000'

In [5]:
response = requests.get(url)

In [6]:
response.status_code

200

In [7]:
data = response.json()

In [8]:
type(data)

list

In [10]:
data

[{'page': 1,
  'pages': 1,
  'per_page': 20000,
  'total': 17490,
  'sourceid': '2',
  'lastupdated': '2026-07-01'},
 [{'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2025',
   'value': 4.27011140706666,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2024',
   'value': 4.77085731915833,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2023',
   'value': 7.39918558080627,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2022',
   'value': 10.8834775726018,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2021',
   'value': 6.82472709282067,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2020',
   'value': 5.19162942092851,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2019',
   'value': 4.10285075461156,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2018',
   'value': 4.6898064677633,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2017',
   'value': 6.22137528933118,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2016',
   'value': 6.44687722255584,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2015',
   'value': 5.09856164363687,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2014',
   'value': 5.52581923392517,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2013',
   'value': 5.74883133553454,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2012',
   'value': 9.15870843167905,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2011',
   'value': 8.97120640995788,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2010',
   'value': 5.53753791645676,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2009',
   'value': 8.95421802392949,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2008',
   'value': 12.5666446595157,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2007',
   'value': 8.45077480635,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2006',
   'value': 8.89816380214033,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2005',
   'value': 8.55803802239778,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2004',
   'value': 5.02342068616285,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2003',
   'value': 7.44970014007366,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2002',
   'value': 8.76375520313543,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2001',
   'value': 5.84035398311557,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2000',
   'value': 8.60148514851491,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1999',
   'value': 7.81986477630862,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1998',
   'value': 7.49525542305607,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1997',
   'value': 10.2495987403066,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1996',
   'value': 9.70658632526504,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1995',
   'value': 12.2885912601426,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1994',
   'value': 14.8528149833969,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1993',
   'value': 13.1356607683724,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1992',
   'value': 16.1676123963339,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1991',
   'value': 17.6781002638523,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1990',
   'value': 12.4579139789566,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1989',
   'value': 12.5582020707012,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1988',
   'value': 12.5222580655931,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1987',
   'value': 12.5634432211069,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1986',
   'value': 13.8919716455565,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1985',
   'value': 13.0065664218827,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1984',
   'value': 10.9838625715774,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1983',
   'value': 11.5675243834069,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1982',
   'value': 12.1399176954734,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1981',
   'value': 14.4615910742106,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1980',
   'value': 15.0665115372509,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1979',
   'value': 15.0698498241015,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1978',
   'value': 12.5268925146401,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1977',
   'value': 14.2380554942681,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1976',
   'value': 11.2164812938294,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1975',
   'value': 15.2240989352891,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1974',
   'value': 19.5983935742148,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1973',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1972',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1971',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1970',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1969',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1968',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1967',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1966',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1965',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1964',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1963',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1962',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1961',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1960',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2025',
   'value': 1.65781767585277,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'FP.CPI.TOTL.ZG',
    'value': 'Inflation, consumer prices (annual %)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2024',

In [11]:
data[0]

{'page': 1,
 'pages': 1,
 'per_page': 20000,
 'total': 17490,
 'sourceid': '2',
 'lastupdated': '2026-07-01'}

In [12]:
data[1][0]

{'indicator': {'id': 'FP.CPI.TOTL.ZG',
  'value': 'Inflation, consumer prices (annual %)'},
 'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
 'countryiso3code': 'AFE',
 'date': '2025',
 'value': 4.27011140706666,
 'unit': '',
 'obs_status': '',
 'decimal': 1}

In [13]:
records = data[1]

In [14]:
df = pd.DataFrame(records)

In [15]:
df.shape

(17490, 8)

In [16]:
df.columns

Index(['indicator', 'country', 'countryiso3code', 'date', 'value', 'unit',
       'obs_status', 'decimal'],
      dtype='object')

In [17]:
df = df[['country', 'countryiso3code', 'date', 'value']]

In [18]:
df.head()

,country,countryiso3code,date,value
0,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2025,4.270111
1,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2024,4.770857
2,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2023,7.399186
3,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2022,10.883478
4,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2021,6.824727

# Data Cleaning

In [19]:
df['country'] = df['country'].applylambda x : x['value'])

In [22]:
df.sample(10)

                        country countryiso3code  date      value
6419                       Cuba             CUB  2008        NaN
12316                     Nepal             NPL  1985   8.052641
11024                    Malawi             MWI  2023  28.789743
9790                 Kazakhstan             KAZ  2003   6.438218
11033                    Malawi             MWI  2014  23.792065
6468                    Curacao             CUW  2025        NaN
3457                    Andorra             AND  2000        NaN
10118                    Kosovo             XKX  2005  -1.385189
15249  St. Martin (French part)             MAF  2022        NaN
12091                   Myanmar             MMR  2012   1.467583

In [24]:
tan_df = df[df['countryiso3code'] == 'TZA']

In [25]:
tan_df

        country countryiso3code  date     value
15774  Tanzania             TZA  2025  3.326974
15775  Tanzania             TZA  2024  3.056947
15776  Tanzania             TZA  2023  3.799233
15777  Tanzania             TZA  2022  4.350272
15778  Tanzania             TZA  2021  3.690920
...         ...             ...   ...       ...
15835  Tanzania             TZA  1964       NaN
15836  Tanzania             TZA  1963       NaN
15837  Tanzania             TZA  1962       NaN
15838  Tanzania             TZA  1961       NaN
15839  Tanzania             TZA  1960       NaN

[66 rows x 4 columns]

In [27]:
df.isna().sum()

country               0
countryiso3code       0
date                  0
value              6018
dtype: int64

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df.to_csv('inflation.csv', index = False)