In [1]:
import numpy as np
import pandas as pd
import requests

In [2]:
url = 'https://api.worldbank.org/v2/country/all/indicator/NE.GDI.TOTL.ZS?format=json&per_page=20000'

In [3]:
response = requests.get(url)

In [4]:
response.status_code

200

In [5]:
data = response.json()

In [6]:
type(data)

list

In [7]:
data[0]

{'page': 1,
 'pages': 1,
 'per_page': 20000,
 'total': 17490,
 'sourceid': '2',
 'lastupdated': '2026-07-01'}

In [8]:
data[1][0]

{'indicator': {'id': 'NE.GDI.TOTL.ZS',
  'value': 'Gross capital formation (% of GDP)'},
 'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
 'countryiso3code': 'AFE',
 'date': '2025',
 'value': 18.192574724704,
 'unit': '',
 'obs_status': '',
 'decimal': 0}

In [10]:
df = pd.DataFrame(data[1])

In [11]:
df.head()

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"{'id': 'NE.GDI.TOTL.ZS', 'value': 'Gross capit...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2025,18.192575,,,0
1,"{'id': 'NE.GDI.TOTL.ZS', 'value': 'Gross capit...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2024,18.509686,,,0
2,"{'id': 'NE.GDI.TOTL.ZS', 'value': 'Gross capit...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2023,19.843989,,,0
3,"{'id': 'NE.GDI.TOTL.ZS', 'value': 'Gross capit...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2022,20.460209,,,0
4,"{'id': 'NE.GDI.TOTL.ZS', 'value': 'Gross capit...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2021,19.643056,,,0

In [12]:
df.columns

Index(['indicator', 'country', 'countryiso3code', 'date', 'value', 'unit',
       'obs_status', 'decimal'],
      dtype='object')

In [13]:
df = df[['country', 'countryiso3code', 'date', 'value']]

In [14]:
df.head()

,country,countryiso3code,date,value
0,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2025,18.192575
1,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2024,18.509686
2,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2023,19.843989
3,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2022,20.460209
4,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2021,19.643056

In [16]:
df['country'] = df['country'].apply(lambda x : x['value'])

In [17]:
df.head()

                       country countryiso3code  date      value
0  Africa Eastern and Southern             AFE  2025  18.192575
1  Africa Eastern and Southern             AFE  2024  18.509686
2  Africa Eastern and Southern             AFE  2023  19.843989
3  Africa Eastern and Southern             AFE  2022  20.460209
4  Africa Eastern and Southern             AFE  2021  19.643056

In [18]:
df.isnull().sum()

country               0
countryiso3code       0
date                  0
value              6569
dtype: int64

In [19]:
df.to_csv('capital.csv', index = False)