In [1]:
import numpy as np
import pandas as pd
import requests

In [5]:
url = 'https://api.worldbank.org/v2/country/all/indicator/NE.EXP.GNFS.ZS?format=json&per_page=20000'

In [6]:
response = requests.get(url)

In [7]:
response.status_code

200

In [8]:
data = response.json()

In [9]:
type(data)

list

In [10]:
data

[{'page': 1,
  'pages': 1,
  'per_page': 20000,
  'total': 17490,
  'sourceid': '2',
  'lastupdated': '2026-07-01'},
 [{'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2025',
   'value': 25.5665587243646,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2024',
   'value': 25.5215824374484,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2023',
   'value': 26.1604657168212,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2022',
   'value': 27.0330789398506,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2021',
   'value': 25.7282688404396,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2020',
   'value': 22.1912368193954,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2019',
   'value': 23.9488254031749,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2018',
   'value': 25.3367082736352,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2017',
   'value': 23.7950438337964,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2016',
   'value': 23.6847419806965,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2015',
   'value': 23.908542224775,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2014',
   'value': 27.7424183258334,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2013',
   'value': 28.8108336643313,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2012',
   'value': 29.4705342149546,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2011',
   'value': 30.9777286742066,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2010',
   'value': 29.0142188659107,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2009',
   'value': 26.9152499176512,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2008',
   'value': 34.9231992557532,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2007',
   'value': 31.5737589559961,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2006',
   'value': 29.2337914845654,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2005',
   'value': 27.4187648320494,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2004',
   'value': 25.5076384535665,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2003',
   'value': 25.3435760791817,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2002',
   'value': 27.535691175228,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2001',
   'value': 27.2075547915452,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2000',
   'value': 25.5458281643018,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1999',
   'value': 24.7346970094741,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1998',
   'value': 24.8101365318032,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1997',
   'value': 24.4832899559001,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1996',
   'value': 25.4019688189712,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1995',
   'value': 24.2987159258599,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1994',
   'value': 23.6342975939517,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1993',
   'value': 22.6439229212955,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1992',
   'value': 21.4602727582505,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1991',
   'value': 18.4391931443722,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1990',
   'value': 20.3024567059601,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1989',
   'value': 22.0249422039509,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1988',
   'value': 23.6881179874589,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1987',
   'value': 24.6031276578107,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1986',
   'value': 23.3215170977892,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1985',
   'value': 22.0005520706988,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1984',
   'value': 20.7227471768736,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1983',
   'value': 20.0825011556428,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1982',
   'value': 20.4726753334678,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1981',
   'value': 22.7477531736348,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1980',
   'value': 27.9022727381184,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1979',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1978',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1977',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1976',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1975',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1974',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1973',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1972',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1971',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1970',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1969',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1968',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1967',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1966',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1965',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1964',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1963',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1962',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1961',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1960',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2025',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.EXP.GNFS.ZS',
    'value': 'Exports of goods and services (% of GDP)'},

In [11]:
data[0]

{'page': 1,
 'pages': 1,
 'per_page': 20000,
 'total': 17490,
 'sourceid': '2',
 'lastupdated': '2026-07-01'}

In [12]:
data[1][0]

{'indicator': {'id': 'NE.EXP.GNFS.ZS',
  'value': 'Exports of goods and services (% of GDP)'},
 'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
 'countryiso3code': 'AFE',
 'date': '2025',
 'value': 25.5665587243646,
 'unit': '',
 'obs_status': '',
 'decimal': 1}

In [13]:
records = data[1]

In [14]:
df = pd.DataFrame(records)

In [16]:
df.shape

(17490, 8)

In [17]:
df.columns

Index(['indicator', 'country', 'countryiso3code', 'date', 'value', 'unit',
       'obs_status', 'decimal'],
      dtype='object')

In [18]:
df = df[['country', 'countryiso3code', 'date', 'value']]

In [19]:
df.head()

,country,countryiso3code,date,value
0,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2025,25.566559
1,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2024,25.521582
2,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2023,26.160466
3,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2022,27.033079
4,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2021,25.728269

# Data cleaning

In [20]:
df['country'] = df['country'].apply(lambda x : x['value'])

In [21]:
df.head()

                       country countryiso3code  date      value
0  Africa Eastern and Southern             AFE  2025  25.566559
1  Africa Eastern and Southern             AFE  2024  25.521582
2  Africa Eastern and Southern             AFE  2023  26.160466
3  Africa Eastern and Southern             AFE  2022  27.033079
4  Africa Eastern and Southern             AFE  2021  25.728269

In [22]:
df.isnull().sum()

country               0
countryiso3code       0
date                  0
value              6100
dtype: int64

In [24]:
df.to_csv('exports.csv', index = False)