In [1]:
import numpy as np
import pandas as pd
import requests

In [2]:
url = 'https://api.worldbank.org/v2/country/all/indicator/BX.KLT.DINV.WD.GD.ZS?format=json&per_page=20000'

In [3]:
response = requests.get(url)

In [4]:
response.status_code

200

In [5]:
data = response.json()

In [6]:
type(data)

list

In [7]:
data

[{'page': 1,
  'pages': 1,
  'per_page': 20000,
  'total': 17490,
  'sourceid': '2',
  'lastupdated': '2026-07-01'},
 [{'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2025',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2024',
   'value': 2.14227343586629,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2023',
   'value': 1.96226870934897,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2022',
   'value': 1.72140037683879,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2021',
   'value': 4.91733778368595,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2020',
   'value': 1.42136722132285,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2019',
   'value': 1.48113722956682,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2018',
   'value': 1.29620160072117,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2017',
   'value': 1.03974029154369,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2016',
   'value': 2.01086478850792,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2015',
   'value': 3.15374863446916,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2014',
   'value': 2.7750793200763,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2013',
   'value': 2.19676625195527,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2012',
   'value': 2.54477763727581,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2011',
   'value': 1.85627659158709,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2010',
   'value': 1.64104298925317,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2009',
   'value': 2.58658904823285,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2008',
   'value': 3.15720320548687,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2007',
   'value': 2.43759936837759,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2006',
   'value': 1.25673060404142,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2005',
   'value': 2.02191300436881,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2004',
   'value': 1.82591614109993,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2003',
   'value': 2.44332327879929,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2002',
   'value': 2.45311397861766,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2001',
   'value': 4.77476973739498,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2000',
   'value': 1.53405599658526,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1999',
   'value': 2.40573082549953,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1998',
   'value': 1.57047655313223,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1997',
   'value': 2.0450381039679,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1996',
   'value': 0.781600201179913,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1995',
   'value': 0.996380779254468,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1994',
   'value': 0.498141355701143,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1993',
   'value': 0.356989982348683,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1992',
   'value': 0.276113112201507,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1991',
   'value': 0.461006030428787,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1990',
   'value': 0.0370273335943822,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1989',
   'value': 0.186708606304335,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1988',
   'value': 0.266166960598929,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1987',
   'value': 0.149237654619366,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1986',
   'value': 0.264600685235139,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1985',
   'value': 0.0737006919683429,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1984',
   'value': 0.371534097297884,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1983',
   'value': 0.0473911101205504,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1982',
   'value': 0.341398582498488,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1981',
   'value': 0.21098641423966,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1980',
   'value': 0.282531234244915,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1979',
   'value': -0.0120566511079377,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1978',
   'value': 0.136596424263848,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1977',
   'value': 0.0622394120152408,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1976',
   'value': 0.506448418809181,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1975',
   'value': 0.352344501471291,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1974',
   'value': 1.13540552900095,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1973',
   'value': 0.25491938195338,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1972',
   'value': 0.422769067454695,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1971',
   'value': 0.765902085173562,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1970',
   'value': 1.03248516310972,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1969',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1968',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1967',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1966',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1965',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1964',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1963',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
    'value': 'Foreign direct investment, net inflows (% of GDP)'},

In [8]:
data[0]

{'page': 1,
 'pages': 1,
 'per_page': 20000,
 'total': 17490,
 'sourceid': '2',
 'lastupdated': '2026-07-01'}

In [9]:
data[1][0]

{'indicator': {'id': 'BX.KLT.DINV.WD.GD.ZS',
  'value': 'Foreign direct investment, net inflows (% of GDP)'},
 'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
 'countryiso3code': 'AFE',
 'date': '2025',
 'value': None,
 'unit': '',
 'obs_status': '',
 'decimal': 1}

In [10]:
records = data[1]

In [11]:
df = pd.DataFrame(records)

In [12]:
df.head()

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"{'id': 'BX.KLT.DINV.WD.GD.ZS', 'value': 'Forei...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2025,NaN,,,1
1,"{'id': 'BX.KLT.DINV.WD.GD.ZS', 'value': 'Forei...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2024,2.142273,,,1
2,"{'id': 'BX.KLT.DINV.WD.GD.ZS', 'value': 'Forei...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2023,1.962269,,,1
3,"{'id': 'BX.KLT.DINV.WD.GD.ZS', 'value': 'Forei...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2022,1.721400,,,1
4,"{'id': 'BX.KLT.DINV.WD.GD.ZS', 'value': 'Forei...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2021,4.917338,,,1

In [13]:
df.columns

Index(['indicator', 'country', 'countryiso3code', 'date', 'value', 'unit',
       'obs_status', 'decimal'],
      dtype='object')

In [15]:
df.shape

(17490, 8)

In [16]:
df = df[['country', 'countryiso3code', 'date', 'value']]

In [17]:
df.head()

,country,countryiso3code,date,value
0,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2025,NaN
1,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2024,2.142273
2,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2023,1.962269
3,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2022,1.721400
4,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2021,4.917338

In [18]:
df['country'] = df['country'].apply(lambda x : x['value'])

In [19]:
df.head()

                       country countryiso3code  date     value
0  Africa Eastern and Southern             AFE  2025       NaN
1  Africa Eastern and Southern             AFE  2024  2.142273
2  Africa Eastern and Southern             AFE  2023  1.962269
3  Africa Eastern and Southern             AFE  2022  1.721400
4  Africa Eastern and Southern             AFE  2021  4.917338

In [20]:
df.isnull().sum()

country               0
countryiso3code       0
date                  0
value              5753
dtype: int64

In [ ]:
df.to_csv('fd')