In [1]:
import numpy as np
import pandas as pd
import requests

In [2]:
url = 'https://api.worldbank.org/v2/country/all/indicator/NE.CON.GOVT.ZS?format=json&per_page=20000'

In [3]:
response = requests.get(url)

In [4]:
response.status_code

200

In [6]:
data = response.json()

In [7]:
type(data)

list

In [8]:
data

[{'page': 1,
  'pages': 1,
  'per_page': 20000,
  'total': 17490,
  'sourceid': '2',
  'lastupdated': '2026-07-01'},
 [{'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2025',
   'value': 14.8587598682672,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2024',
   'value': 14.8453529889399,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2023',
   'value': 15.0651535647196,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2022',
   'value': 15.4739827901911,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2021',
   'value': 15.3454533741339,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2020',
   'value': 15.9579082911315,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2019',
   'value': 15.4245689648657,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2018',
   'value': 15.3192211588011,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2017',
   'value': 15.766855069193,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2016',
   'value': 15.9485501587196,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2015',
   'value': 15.9844321206349,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2014',
   'value': 16.5073494401501,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2013',
   'value': 17.0382308207548,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2012',
   'value': 16.5189482198196,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2011',
   'value': 16.3157535330138,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2010',
   'value': 15.7372986009467,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2009',
   'value': 15.8299579882435,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2008',
   'value': 15.2060769859483,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2007',
   'value': 14.8981757022528,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2006',
   'value': 14.8400598438231,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2005',
   'value': 15.2335050242801,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2004',
   'value': 15.9365572406839,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2003',
   'value': 16.1063800010854,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2002',
   'value': 15.222169674553,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2001',
   'value': 15.8711280949365,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2000',
   'value': 15.5888851134441,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1999',
   'value': 16.6011082072451,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1998',
   'value': 16.6580582570602,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1997',
   'value': 16.5896686347418,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1996',
   'value': 16.6825183939524,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1995',
   'value': 16.3276559044779,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1994',
   'value': 17.7174841684943,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1993',
   'value': 17.0456989414005,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1992',
   'value': 17.2728825041321,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1991',
   'value': 15.1422214919484,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1990',
   'value': 14.789663419123,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1989',
   'value': 14.3341864250144,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1988',
   'value': 15.0244564826382,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1987',
   'value': 15.7627899978922,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1986',
   'value': 14.3464728030363,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1985',
   'value': 13.1781461313532,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1984',
   'value': 13.8898451818797,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1983',
   'value': 12.793500537052,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1982',
   'value': 12.8351596572125,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1981',
   'value': 12.6137545297297,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1980',
   'value': 12.4542592223609,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1979',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1978',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1977',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1976',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1975',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1974',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1973',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1972',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1971',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1970',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1969',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1968',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1967',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1966',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1965',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1964',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',
    'value': 'General government final consumption expenditure (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1963',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.CON.GOVT.ZS',

In [9]:
data[0]

{'page': 1,
 'pages': 1,
 'per_page': 20000,
 'total': 17490,
 'sourceid': '2',
 'lastupdated': '2026-07-01'}

In [10]:
data[1][0]

{'indicator': {'id': 'NE.CON.GOVT.ZS',
  'value': 'General government final consumption expenditure (% of GDP)'},
 'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
 'countryiso3code': 'AFE',
 'date': '2025',
 'value': 14.8587598682672,
 'unit': '',
 'obs_status': '',
 'decimal': 1}

In [11]:
records = data[1]

In [12]:
df = pd.DataFrame(records)

In [13]:
df.shape

(17490, 8)

In [14]:
df.columns

Index(['indicator', 'country', 'countryiso3code', 'date', 'value', 'unit',
       'obs_status', 'decimal'],
      dtype='object')

In [15]:
df= df[['country', 'countryiso3code', 'date', 'value']]

In [16]:
df.head()

,country,countryiso3code,date,value
0,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2025,14.858760
1,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2024,14.845353
2,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2023,15.065154
3,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2022,15.473983
4,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2021,15.345453

In [18]:
df['country'] = df['country'].apply(lambda x : x['value'])

In [19]:
df.head()

                       country countryiso3code  date      value
0  Africa Eastern and Southern             AFE  2025  14.858760
1  Africa Eastern and Southern             AFE  2024  14.845353
2  Africa Eastern and Southern             AFE  2023  15.065154
3  Africa Eastern and Southern             AFE  2022  15.473983
4  Africa Eastern and Southern             AFE  2021  15.345453

In [20]:
df.isnull().sum()

country               0
countryiso3code       0
date                  0
value              6428
dtype: int64

In [21]:
df.to_csv('gfc.csv', index = False)