In [1]:
import numpy as np
import pandas as pd
import requests

In [2]:
url = 'https://api.worldbank.org/v2/country/all/indicator/NE.IMP.GNFS.ZS?format=json&per_page=20000'

In [3]:
response = requests.get(url)

In [4]:
response.status_code

200

In [5]:
data = response.json()

In [6]:
type(data)

list

In [7]:
data

[{'page': 1,
  'pages': 1,
  'per_page': 20000,
  'total': 17490,
  'sourceid': '2',
  'lastupdated': '2026-07-01'},
 [{'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2025',
   'value': 27.7853990968836,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2024',
   'value': 28.3057372919042,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2023',
   'value': 29.503506685176,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2022',
   'value': 29.4724601086904,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2021',
   'value': 26.2881671327756,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2020',
   'value': 24.2926049272612,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2019',
   'value': 27.2160149136586,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2018',
   'value': 28.4028082334318,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2017',
   'value': 27.4060390362816,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2016',
   'value': 28.6800694143067,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2015',
   'value': 30.7145156933407,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2014',
   'value': 32.9761017814553,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2013',
   'value': 33.7082079879031,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2012',
   'value': 32.6287820033807,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2011',
   'value': 31.6686339451965,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2010',
   'value': 29.4797512451776,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2009',
   'value': 30.693455177231,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2008',
   'value': 35.3087960585733,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2007',
   'value': 31.2924480941032,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2006',
   'value': 29.0338044245994,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2005',
   'value': 27.8066358959493,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2004',
   'value': 26.7112933780207,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2003',
   'value': 26.0115775877922,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2002',
   'value': 27.4190699859071,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2001',
   'value': 26.549361204311,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2000',
   'value': 25.839358809097,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1999',
   'value': 25.6841226438638,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1998',
   'value': 27.191939711821,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1997',
   'value': 26.0584701622431,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1996',
   'value': 26.4178133544527,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1995',
   'value': 25.8777138625327,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1994',
   'value': 24.0321567169117,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1993',
   'value': 21.1983406522708,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1992',
   'value': 21.0555833586769,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1991',
   'value': 19.4652389191039,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1990',
   'value': 19.6424270853207,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1989',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1988',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1987',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1986',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1985',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1984',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1983',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1982',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1981',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1980',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1979',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1978',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1977',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1976',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1975',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1974',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1973',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1972',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1971',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1970',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1969',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1968',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1967',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1966',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1965',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1964',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1963',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1962',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1961',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1960',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2025',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NE.IMP.GNFS.ZS',
    'value': 'Imports of goods and services (% of GDP)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2024',

In [8]:
data[0]

{'page': 1,
 'pages': 1,
 'per_page': 20000,
 'total': 17490,
 'sourceid': '2',
 'lastupdated': '2026-07-01'}

In [11]:
data[1][0]

{'indicator': {'id': 'NE.IMP.GNFS.ZS',
  'value': 'Imports of goods and services (% of GDP)'},
 'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
 'countryiso3code': 'AFE',
 'date': '2025',
 'value': 27.7853990968836,
 'unit': '',
 'obs_status': '',
 'decimal': 1}

In [12]:
records = data[1]

In [13]:
df = pd.DataFrame(records)

In [14]:
df.head()

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"{'id': 'NE.IMP.GNFS.ZS', 'value': 'Imports of ...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2025,27.785399,,,1
1,"{'id': 'NE.IMP.GNFS.ZS', 'value': 'Imports of ...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2024,28.305737,,,1
2,"{'id': 'NE.IMP.GNFS.ZS', 'value': 'Imports of ...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2023,29.503507,,,1
3,"{'id': 'NE.IMP.GNFS.ZS', 'value': 'Imports of ...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2022,29.472460,,,1
4,"{'id': 'NE.IMP.GNFS.ZS', 'value': 'Imports of ...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2021,26.288167,,,1

# Data Cleaning

In [15]:
df.shape

(17490, 8)

In [16]:
df.columns

Index(['indicator', 'country', 'countryiso3code', 'date', 'value', 'unit',
       'obs_status', 'decimal'],
      dtype='object')

In [17]:
df = df[['country', 'countryiso3code', 'date', 'value']]

In [18]:
df.head()

,country,countryiso3code,date,value
0,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2025,27.785399
1,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2024,28.305737
2,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2023,29.503507
3,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2022,29.472460
4,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2021,26.288167

In [19]:
df['country'] = df['country'].apply(lambda x : x['value'])

In [20]:
df.head()

                       country countryiso3code  date      value
0  Africa Eastern and Southern             AFE  2025  27.785399
1  Africa Eastern and Southern             AFE  2024  28.305737
2  Africa Eastern and Southern             AFE  2023  29.503507
3  Africa Eastern and Southern             AFE  2022  29.472460
4  Africa Eastern and Southern             AFE  2021  26.288167

In [21]:
df.isnull().sum()

country               0
countryiso3code       0
date                  0
value              6048
dtype: int64

In [23]:
df.to_csv('imports.csv', index = False)