In [1]:
import numpy as np
import pandas as pd
import requests

In [2]:
url = 'https://api.worldbank.org/v2/country/all/indicator/SP.POP.GROW?format=json&per_page=20000'

In [3]:
response = requests.get(url)

In [4]:
response.status_code

200

In [5]:
data = response.json()

In [6]:
type(data)

list

In [7]:
data

[{'page': 1,
  'pages': 1,
  'per_page': 20000,
  'total': 17490,
  'sourceid': '2',
  'lastupdated': '2026-07-01'},
 [{'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2025',
   'value': 2.51127758940208,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2024',
   'value': 2.47280147854539,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2023',
   'value': 2.51916664518144,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2022',
   'value': 2.59275445199729,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2021',
   'value': 2.6494391643563,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2020',
   'value': 2.69951609745311,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2019',
   'value': 2.72168052257397,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2018',
   'value': 2.73426282366823,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2017',
   'value': 2.64206728810391,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2016',
   'value': 2.64074325542301,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2015',
   'value': 2.69683038788555,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2014',
   'value': 2.70410469635343,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2013',
   'value': 2.7482455829431,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2012',
   'value': 2.69351289263264,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2011',
   'value': 2.68462143269084,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2010',
   'value': 2.73452519643287,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2009',
   'value': 2.73723757208867,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2008',
   'value': 2.72364001522085,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2007',
   'value': 2.69144498343854,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2006',
   'value': 2.66976588552462,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2005',
   'value': 2.65847839652985,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2004',
   'value': 2.64137149821667,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2003',
   'value': 2.61906809457548,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2002',
   'value': 2.60780157535376,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2001',
   'value': 2.5886417713116,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2000',
   'value': 2.59538933998788,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1999',
   'value': 2.62289295632848,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1998',
   'value': 2.59082906065185,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1997',
   'value': 2.56360934676329,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1996',
   'value': 2.64520724063808,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1995',
   'value': 2.59624753960851,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1994',
   'value': 2.65931727355301,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1993',
   'value': 2.76949139016801,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1992',
   'value': 2.66048165065413,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1991',
   'value': 2.75069381267418,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1990',
   'value': 2.86654890669014,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1989',
   'value': 2.82575303796522,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1988',
   'value': 2.9047075526033,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1987',
   'value': 2.99676072743034,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1986',
   'value': 2.987529648733,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1985',
   'value': 3.0109923521529,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1984',
   'value': 3.03401872045451,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1983',
   'value': 3.13265066685359,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1982',
   'value': 3.21559919558012,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1981',
   'value': 3.09317148407782,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1980',
   'value': 2.99895122759029,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1979',
   'value': 3.12908916400582,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1978',
   'value': 2.98952355658372,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1977',
   'value': 2.82959668799219,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1976',
   'value': 2.91729731599594,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1975',
   'value': 2.92186725484821,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1974',
   'value': 2.97492214745766,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1973',
   'value': 2.92057490651803,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1972',
   'value': 2.84260156370146,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1971',
   'value': 2.88686159332995,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1970',
   'value': 2.88850904619344,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1969',
   'value': 2.88945065291198,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1968',
   'value': 2.89053053210213,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1967',
   'value': 2.84481116053896,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1966',
   'value': 2.81032375617882,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1965',
   'value': 2.8098822116255,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1964',
   'value': 2.76985566424139,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1963',
   'value': 2.71404193548623,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1962',
   'value': 2.68700877626946,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1961',
   'value': 2.6246235203985,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '1960',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2025',
   'value': 2.30763633387899,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2024',
   'value': 2.39809620858228,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2023',
   'value': 2.37937619625479,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2022',
   'value': 2.32085084130242,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2021',
   'value': 2.35569541452186,
   'unit': '',
   'obs_status': '',
   'decimal': 1},

In [8]:
data[0]

{'page': 1,
 'pages': 1,
 'per_page': 20000,
 'total': 17490,
 'sourceid': '2',
 'lastupdated': '2026-07-01'}

In [9]:
data[1][0]

{'indicator': {'id': 'SP.POP.GROW', 'value': 'Population growth (annual %)'},
 'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
 'countryiso3code': 'AFE',
 'date': '2025',
 'value': 2.51127758940208,
 'unit': '',
 'obs_status': '',
 'decimal': 1}

In [10]:
df = pd.DataFrame(data[1])

In [11]:
df.shape

(17490, 8)

In [12]:
df.columns

Index(['indicator', 'country', 'countryiso3code', 'date', 'value', 'unit',
       'obs_status', 'decimal'],
      dtype='object')

In [13]:
df = df[['country', 'countryiso3code', 'date', 'value']]

In [14]:
df.head()

,country,countryiso3code,date,value
0,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2025,2.511278
1,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2024,2.472801
2,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2023,2.519167
3,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2022,2.592754
4,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2021,2.649439

In [15]:
df['country'] = df['country'].apply(lambda x : x['value'])

In [16]:
df.head()

                       country countryiso3code  date     value
0  Africa Eastern and Southern             AFE  2025  2.511278
1  Africa Eastern and Southern             AFE  2024  2.472801
2  Africa Eastern and Southern             AFE  2023  2.519167
3  Africa Eastern and Southern             AFE  2022  2.592754
4  Africa Eastern and Southern             AFE  2021  2.649439