In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../data/processed/finale_clean.csv')

In [3]:
df['Net_Exports'] = df['exports'] - df['imports']

In [4]:
df = df.drop(columns = ['imports' , 'exports'] )

In [5]:
df = df.dropna(subset=["gdp_growth"])

In [6]:
X = df.drop(columns = ['gdp_growth']) 
y = df['gdp_growth']

In [7]:
X.head()

,country,countryiso3code,date,inf,ump,pop,fdi,capital,govt,Net_Exports
1,Afghanistan,AFG,2024,-6.601186,13.687,2.836573,NaN,17.086890,23.626196,-52.357521
2,Afghanistan,AFG,2023,-4.644709,14.008,2.135594,NaN,15.292482,21.214515,-34.529021
3,Afghanistan,AFG,2022,13.712102,14.100,1.435704,NaN,16.700000,21.845492,-36.125385
4,Afghanistan,AFG,2021,5.133203,12.006,2.356098,0.144467,13.000000,21.262384,-22.727411
5,Afghanistan,AFG,2020,5.601888,11.710,3.153609,0.064994,11.500000,22.109219,-25.868260

In [8]:
y.head()

1     1.873193
2     2.266944
3    -6.240172
4   -20.738839
5    -2.351101
Name: gdp_growth, dtype: float64

In [9]:
df["date"] = pd.to_datetime(df["date"])
df['year'] = df['date'].dt.year

In [10]:
df.drop(columns=['date'])

,country,countryiso3code,gdp_growth,inf,ump,pop,fdi,capital,govt,Net_Exports,year
1,Afghanistan,AFG,1.873193,-6.601186,13.687,2.836573,NaN,17.086890,23.626196,-52.357521,1970
2,Afghanistan,AFG,2.266944,-4.644709,14.008,2.135594,NaN,15.292482,21.214515,-34.529021,1970
3,Afghanistan,AFG,-6.240172,13.712102,14.100,1.435704,NaN,16.700000,21.845492,-36.125385,1970
4,Afghanistan,AFG,-20.738839,5.133203,12.006,2.356098,0.144467,13.000000,21.262384,-22.727411,1970
5,Afghanistan,AFG,-2.351101,5.601888,11.710,3.153609,0.064994,11.500000,22.109219,-25.868260,1970
...,...,...,...,...,...,...,...,...,...,...,...
14316,Zimbabwe,ZWE,4.910571,NaN,NaN,3.154707,NaN,13.652441,11.238064,NaN,1970
14317,Zimbabwe,ZWE,-1.106172,NaN,NaN,3.154055,NaN,11.742325,11.703759,NaN,1970
14318,Zimbabwe,ZWE,6.244345,NaN,NaN,3.152908,NaN,11.513209,12.866399,NaN,1970
14319,Zimbabwe,ZWE,1.434471,NaN,NaN,3.144570,NaN,15.598707,12.055163,NaN,1970
14320,Zimbabwe,ZWE,6.316157,NaN,NaN,3.127265,NaN,20.049978,11.611307,NaN,1970

In [11]:
df.head()

,country,countryiso3code,date,gdp_growth,inf,ump,pop,fdi,capital,govt,Net_Exports,year
1,Afghanistan,AFG,1970-01-01 00:00:00.000002024,1.873193,-6.601186,13.687,2.836573,NaN,17.086890,23.626196,-52.357521,1970
2,Afghanistan,AFG,1970-01-01 00:00:00.000002023,2.266944,-4.644709,14.008,2.135594,NaN,15.292482,21.214515,-34.529021,1970
3,Afghanistan,AFG,1970-01-01 00:00:00.000002022,-6.240172,13.712102,14.100,1.435704,NaN,16.700000,21.845492,-36.125385,1970
4,Afghanistan,AFG,1970-01-01 00:00:00.000002021,-20.738839,5.133203,12.006,2.356098,0.144467,13.000000,21.262384,-22.727411,1970
5,Afghanistan,AFG,1970-01-01 00:00:00.000002020,-2.351101,5.601888,11.710,3.153609,0.064994,11.500000,22.109219,-25.868260,1970

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [13]:
X_train.isna().sum()

country               0
countryiso3code       0
date                  0
inf                2044
ump                4051
pop                   1
fdi                1882
capital            2338
govt               2282
Net_Exports        2087
dtype: int64

In [14]:
y_train.isna().sum()

np.int64(0)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11406 entries, 1 to 14320
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          11406 non-null  object
 1   countryiso3code  11406 non-null  object
 2   date             11406 non-null  datetime64[ns]
 3   gdp_growth       11406 non-null  float64
 4   inf              8869 non-null   float64
 5   ump              6321 non-null   float64
 6   pop              11404 non-null  float64
 7   fdi              9083 non-null   float64
 8   capital          8508 non-null   float64
 9   govt             8576 non-null   float64
 10  Net_Exports      8826 non-null   float64
 11  year             11406 non-null  int32
dtypes: datetime64[ns](1), float64(8), int32(1), object(2)
memory usage: 1.1+ MB

In [16]:
df.isna().sum()

country               0
countryiso3code       0
date                  0
gdp_growth            0
inf                2537
ump                5085
pop                   2
fdi                2323
capital            2898
govt               2830
Net_Exports        2580
year                  0
dtype: int64

In [17]:
cat_cols = X_train.select_dtypes(include = 'object').columns
num_cols = X_train.select_dtypes(exclude = 'object').columns

In [18]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer

In [19]:
num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [20]:
cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OrdinalEncoder(handle_unknown="use_encoded_value",
                               unknown_value=-1))
])

In [21]:
preprocessor = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])

In [22]:
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

In [23]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train_transformed, y_train)

y_pred = lr.predict(X_test_transformed)

In [24]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("MAE :", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2  :", r2_score(y_test, y_pred))

MAE : 3.748318120813513
RMSE: 6.276929063184005
R2  : 0.06276923212281604

In [25]:
from xgboost import XGBRegressor

xgb = XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    random_state=42
)

xgb.fit(X_train_transformed, y_train)

y_pred_xgb = xgb.predict(X_test_transformed)

In [26]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("MAE :", mean_absolute_error(y_test, y_pred_xgb))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_xgb)))
print("R2  :", r2_score(y_test, y_pred_xgb))

MAE : 3.4110840419724378
RMSE: 5.703348407282436
R2  : 0.22622997528747235

In [27]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train_transformed, y_train)

y_pred_rf = rf.predict(X_test_transformed)

In [28]:
print("MAE :", mean_absolute_error(y_test, y_pred_rf))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))
print("R2  :", r2_score(y_test, y_pred_rf))

MAE : 3.3845285591350804
RMSE: 5.795774271376393
R2  : 0.2009480395599743

# Classification Project

In [29]:
def categorize_growth(x):
    if x < 0:
        return 'Recession'
    elif x < 3:
        return 'Slow Growth'
    else:
        return 'Strong Growth'

df['growth_category'] = df['gdp_growth'].apply(categorize_growth)
df['growth_category'].value_counts()

growth_category
Strong Growth    6622
Slow Growth      2794
Recession        1990
Name: count, dtype: int64

In [30]:
train = df[df['year'] < 2020]
test = df[df['year'] >= 2020]

feature_cols = [c for c in df.columns if c not in ['gdp_growth','growth_category','growth_category_enc','date']]

X_train, y_train = train[feature_cols], train['growth_category_enc']
X_test, y_test = test[feature_cols], test['growth_category_enc']

KeyError: 'growth_category_enc'